name: Consumer-Workflow

on:
  push:
    branches: [dev, qa, uat, preprod, main]
  pull_request:
    branches: [main]

jobs:
  dockerfile-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: Dockerfile

  build-test:
    runs-on: ubuntu-latest
    needs: dockerfile-lint

    steps:
      - uses: actions/checkout@v4

      - name: Run build
        run: make build

      - name: Run test
        run: make test

  deploy-dev:
    needs: build-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    uses: lishsuki-maker/gh-sharedrepo/.github/workflows/deploy.yml@main
    with:
      environment: dev
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}

  deploy-qa:
    needs: build-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/qa'
    uses: lishsuki-maker/gh-sharedrepo/.github/workflows/deploy.yml@main
    with:
      environment: qa
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}

  deploy-uat:
    needs: build-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/uat'
    uses: lishsuki-maker/gh-sharedrepo/.github/workflows/deploy.yml@main
    with:
      environment: uat
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}

  deploy-preprod:
    needs: build-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/preprod'
    uses: lishsuki-maker/gh-sharedrepo/.github/workflows/deploy.yml@main
    with:
      environment: preprod
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}

  deploy-prod:
    needs: build-test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: lishsuki-maker/gh-sharedrepo/.github/workflows/deploy.yml@main
    with:
      environment: prod
    secrets:
      aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
